// <auto-generated />
using DB_Validate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBValidate.Migrations;

[DbContext(typeof(DbvalidateContext))]
partial class DbvalidateContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("DB_Validate.Models.dbvalidate", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("CPF")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("varchar(14)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("cont")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("dbvalidates");
            });
#pragma warning restore 612, 618
    }
}
